CREATE TABLE T_PEOPLE (
    ID SERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(90) NOT NULL,
    PIN VARCHAR(10)
);

CREATE TABLE T_ADDRESSES (
    ID SERIAL PRIMARY KEY,
    T_PEOPLE_ID INTEGER NOT NULL,
    ADDR_TYPE VARCHAR(5) NOT NULL,
    ADDR_INFO VARCHAR(300),
    FOREIGN KEY (T_PEOPLE_ID) REFERENCES T_PEOPLE(ID)
);

CREATE TABLE T_MAILS (
    ID SERIAL PRIMARY KEY,
    T_PEOPLE_ID INTEGER NOT NULL,
    EMAIL_TYPE VARCHAR(5) NOT NULL,
    EMAIL VARCHAR(40),
    FOREIGN KEY (T_PEOPLE_ID) REFERENCES T_PEOPLE(ID)
);